Repository CheesecakeLabs/react-next-boilerplate, pull requests merged in 2018-08, with the labels that each got.

#28 Git Hooks
  .eslintrc.json
  next.config.js
  package.json
  src/pages/_document.js
  yarn.lock
Labels: ready to review

#30 Eslint Fixes
  .babelrc
  .eslintrc.json
  components/atoms/button/index.js
  components/atoms/input/index.stories.js
  components/atoms/modal/index.stories.js
  components/molecules/checkbox/index.stories.js
  components/molecules/radio/index.stories.js
  next.config.js
  package.json
  src/pages/index/index.js
  yarn.lock
Labels: bug, ready to review

#16 Bia/feature side menu
  components/assets/icons/close.png
  components/assets/icons/menu.png
  components/atoms/button/icon.js
  components/atoms/button/index.js
  components/atoms/button/index.stories.js
  components/atoms/icon/index.stories.js
  components/atoms/logo/index.js
  components/atoms/logo/styles.css
  components/molecules/app-bar/index.js
  components/molecules/app-bar/styles.css
  components/organisms/vertical-nav/drawer.js
  components/organisms/vertical-nav/footer.js
  components/organisms/vertical-nav/index.js
  components/organisms/vertical-nav/index.stories.js
  components/organisms/vertical-nav/item.js
  components/organisms/vertical-nav/items.js
  components/organisms/vertical-nav/styles.css
  src/pages/index/index.js
  storybook/assets/icons/ckl-logo.png
  storybook/assets/icons/logo.png
  storybook/assets/icons/settings.png
Labels: ready to merge

#26 Pattyssilveira/accordion component
  components/molecules/accordion/index.js
  components/molecules/accordion/index.stories.js
  components/molecules/accordion/section.js
  components/molecules/accordion/styles.css
  src/components/atoms/.gitkeep
  src/components/molecules/.gitkeep
  src/components/organisms/.gitkeep
  src/config/css-variables.js
Labels: ready to review

#10 Bia/feature image upload
  README.md
  components/assets/icons/close-icon.svg
  components/atoms/helper/index.js
  components/atoms/helper/index.stories.js
  components/atoms/helper/styles.css
  components/atoms/image/index.js
  components/atoms/image/styles.css
  components/atoms/loader/index.js
  components/atoms/loader/index.stories.js
  components/atoms/loader/styles.css
  components/atoms/modal/index.stories.js
  components/atoms/overlay/index.js
  components/atoms/overlay/index.stories.js
  components/atoms/overlay/styles.css
  components/molecules/accordion/index.stories.js
  components/molecules/avatar/index.js
  components/molecules/avatar/index.stories.js
  components/molecules/avatar/styles.css
  components/molecules/dialog/index.js
  components/molecules/dialog/index.stories.js
  components/molecules/dialog/styles.css
  components/molecules/image-crop/index.js
  components/molecules/image-crop/index.stories.js
  components/molecules/image-crop/styles.css
  components/molecules/webcam-capture/index.js
  components/molecules/webcam-capture/styles.css
  components/organisms/dialog-capture-image/index.js
  components/organisms/dialog-capture-image/styles.css
  components/organisms/dialog-preview-image/index.js
  components/organisms/dialog-preview-image/styles.css
  components/organisms/editable-image/index.js
  components/organisms/editable-image/index.stories.js
  components/organisms/editable-image/styles.css
  components/utils/.gitkeep
  components/utils/file-validations.js
  package.json
  src/config/css-variables.js
  src/images/ckl-logo.png
  src/images/profile-placeholder.png
  src/images/upload-icon.png
  src/pages/_app.js
  src/pages/_document.js
  src/utils/file-validations.js
  storybook/preview-head.html
  yarn.lock
Labels: needs refactor
